# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
# https://github.com/replicatedhq/local-volume-provider

# daemonset required for file system backup modules when volume snapshots are not supported:
# https://velero.io/docs/v1.16/file-system-backup/
deployNodeAgent: true

nodeAgent:
  podVolumePath: "/var/lib/k0s/kubelet/pods"
  pluginVolumePath: "/var/lib/k0s/kubelet/plugins"
  resources: {}

initContainers:
  - name: velero-plugin-local
    image: replicated/local-volume-provider:0.6.10
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: local
      provider: replicated.com/hostpath
      bucket: velero-hostpath
      default: true
      config:
        path: /home/ju/velero-local-backups


backupsEnabled: true
snapshotsEnabled: false

# TODO: kopia is default and restic won't be able to create backups with velero >1.16,
#       but kopia is not supported by local-volume-provider
# https://github.com/replicatedhq/local-volume-provider/issues/32
# https://github.com/vmware-tanzu/velero/issues/6197
uploaderType: "restic"

# TODO: needs to be configured somewhere
#data:
#  repository-password: "changeme"
