---
# Source: crowdsec-web-ui/charts/crowdsec-web-ui/charts/longhornstorage/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-web-ui-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi