apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: ${KARGO_PROJECT}
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${REPO_URL}
  username: ${GITEA_USER}
  password: ${GITEA_TOKEN}