# Source: postgresdb/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  target:
    name: s3-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ACCESS_KEY_ID: |-
          {{ index . "ACCESS_KEY_ID" }}
        ACCESS_SECRET_KEY: |-
          {{ index . "ACCESS_SECRET_KEY" }}
  data:
    - secretKey: ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b8223814-7afc-43f1-9d62-b3a400b3002e
        property: username
    - secretKey: ACCESS_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b8223814-7afc-43f1-9d62-b3a400b3002e
        property: password