# Source: postgresdb/charts/plugin-barman-cloud/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: plugin-barman-cloud-0.7.1
    app.kubernetes.io/name: plugin-barman-cloud
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/version: "v0.14.0"
    app.kubernetes.io/managed-by: Helm
  name: cnpg-plugin-barman-cloud
  namespace: cloudnative-pg