include:
  - component: $CI_SERVER_FQDN/to-be-continuous/helm/gitlab-ci-helm@8.2.0
    inputs:
      repos: ""
      publish-on: protected
      publish-strategy: none
      chart-dir: "03_apps/charts/wrapper"
