version: '3.3'
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/transmission:/data
      - /services/transmission/settings:/settings
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1333
      - PGID=1333
      - TRANSMISSION_UMASK=007
      - TRANSMISSION_HOME=/settings
      - TRANSMISSION_DOWNLOAD_DIR=/data
      - TRANSMISSION_INCOMPLETE_DIR=/data/.incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/.watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
#      - TRANSMISSION_WEB_UI=combustion
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=
      - OPENVPN_USERNAME=$VPN_USER
      - OPENVPN_PASSWORD=$VPN_PASSWORD
      #- TRANSMISSION_RPC_USERNAME=$WEB_USER
      #- TRANSMISSION_RPC_PASSWORD=$WEB_PASSWORD
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - LOCAL_NETWORK=10.0.0.0/22
      # mssfix: https://github.com/haugene/docker-transmission-openvpn/issues/257
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - CREATE_TUN_DEVICE=false
    ports:
      - '8080:9091'
    image: haugene/transmission-openvpn
    devices:
      - /dev/net/tun
