---
# Source: traefik-external/charts/traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik-external
  namespace: traefik-external
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-external-traefik-external
    helm.sh/chart: traefik-41.1.0
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false