ports:
  traefik:
    expose: 
      default: false  # TODO: turn off in production

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    # -- Load Kubernetes IngressRoute provider
    enabled: false

  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true  # required for argo to not show ingresses as progressing

logs:
  access:
    enabled: true
  general:
    level: INFO

# https://community.traefik.io/t/traefik-ingress-not-getting-loadbalancer-ip/17445/3
#additionalArguments:
#  - "--providers.kubernetesingress.ingressendpoint.publishedservice=default/traefik"
