ingress:
  enabled: true
  host: traefik.k8s-test-1.local

traefik:
  ports:
    traefik:
      expose: 
        default: false  # TODO: turn off in production

  ingressRoute:
    dashboard:
      enabled: false  # enabling this requires traefik crds and the IngressRoute is weird
      matchRule: "Host(`traefik.k8s-test-1.local`)"

  providers:
    kubernetesCRD:
      # -- Load Kubernetes IngressRoute provider
      enabled: false

    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true  # required for argo to not show ingresses as progressing

  logs:
    access:
      enabled: true
    general:
      level: INFO

  # TODO: not in production
  globalArguments:
    - "--api.dashboard=true"
    - "--api.insecure=true"

  # https://community.traefik.io/t/traefik-ingress-not-getting-loadbalancer-ip/17445/3
  #additionalArguments:
  #  - "--providers.kubernetesingress.ingressendpoint.publishedservice=default/traefik"
