# Source: postgresdb/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-superuser
spec:
  target:
    name: db-superuser
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ index . "password" }}
        username: |-
          {{ index . "username" }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 83c71120-85b4-4bab-ac41-b3c500cb4087
        property: password
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 83c71120-85b4-4bab-ac41-b3c500cb4087
        property: username