# Source: postgresdb/templates/pg-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresdb-gen-002-scheduled-backup
  labels:
    app.kubernetes.io/component: database-backup
spec:
  schedule: "0 0 3,15 * * *"
  backupOwnerReference: self  # vs. cluster
  immediate: false
  cluster:
    name: postgresdb-gen-002

  # configure backup type - https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#performing-a-base-backup
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io