# https://docs.crowdsec.net/docs/next/configuration/values_parameters
# https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/README.md
container_runtime: containerd

agent:
  acquisition:
    - namespace: traefik-external
      podName: traefik-external-*
      program: traefik

  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik crowdsecurity/http-cve"

appsec:
  enabled: false  # TODO

lapi:
  podLabels:
    custom.network/postgresdb: egress

  env:
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: bouncer_api_key

    # To enroll the Security Engine to the console
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: enroll_key
    - name: ENROLL_TAGS
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: enroll_tags
    - name: ENROLL_INSTANCE_NAME
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets          
          key: enroll_instance_name

    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: crowdsec-pgcreds
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-pgcreds
          key: password
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: crowdsec-pgcreds
          key: dbname
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: crowdsec-pgcreds
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: crowdsec-pgcreds
          key: port

  persistentVolume:
    data:
      enabled: false
    config:
      enabled: false

secrets:
  externalSecret:
    name: crowdsec-secrets
    csLapiSecretKey: cs_lapi_secret
    registrationTokenKey: registration_token

config:
  config.yaml.local: |
    api:
      client:
        # the log processor will remove delete itself from LAPI when stopping.    
        unregister_on_exit: true
      server:
        # This is needed for agent autoregistration
        auto_registration: # Activate if not using TLS for authentication
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges:
            - "10.243.0.0/16"  # test cluster
            - "10.245.0.0/16"  # prod cluster
    # Using a database is strongly encouraged.
    db_config:
      type: postgresql
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      db_name: ${DB_NAME}
      host: ${DB_HOST}
      port: ${DB_PORT}
      flush:
        bouncers_autodelete:
          api_key: 1h
        agents_autodelete:
          login_password: 1h