apiVersion: v2
name: cert-manager
type: application
version: 0.1.0

dependencies:
  - name: cert-manager
    version: v1.21.2
    repository: oci://quay.io/jetstack/charts

  - name: networkpolicy
    version: 5.1.0
    repository: oci://ghcr.io/lunarys/charts
