helm:
  chart: cert-manager
  version: v1.19.1
  repo: oci://quay.io/jetstack/charts

settings:
  # cert-manager places its leader-election roles and objects in the kube-system namespace
  additionalNamespaces:
    - kube-system
  skipCrds: false
