helm:
  chart: cert-manager
  version: v1.19.1
  repo: quay.io/jetstack/charts  # omit oci:// for argocd compatibility

settings:
  # cert-manager places its leader-election roles and objects in the kube-system namespace
  additionalNamespaces:
    - kube-system
  skipCrds: false
