ingress:
  host: dashboard.svc.elda

image:
  # https://github.com/linuxserver/Heimdall
  # https://github.com/linuxserver/docker-heimdall
  name: lscr.io/linuxserver/heimdall
  tag: 2.7.6

service:
  targetPort: 80

env:
  TZ: Europe/Berlin
  PUID: "1000"
  PGID: "1000"

longhornstorage:
  volumes:
    config:
      size: 200Mi
      variant: encrypted  # unencrypted credentials in the db...
      pvName: "pvc-99e17d16-75ff-4e5e-9aee-28914ff6b3db"
      mount:
        path: /config

podSecurityContextPreset:
  runAsNonRoot: false  # s6-overlay init runs as root before dropping to PUID/PGID
  runAsUser: 0
  fsGroup: 1000


# TODO: access local ca HTTPS endpoints...
# https://github.com/linuxserver/Heimdall#self-signed-certificates-and-local-cas


containerSecurityContextPreset:
  capabilities:
    drop:
      - ALL
    add:
      - SETGID  # drop from root to PGID after init
      - SETUID  # drop from root to PUID after init
      - CHOWN   # set /config ownership to PUID:PGID on first start
      - DAC_OVERRIDE  # sed writes to abc-owned .env on every start
      - NET_BIND_SERVICE  # nginx listens on port 80 (and is not exposed via settings)
      # ls.io init tries to make nginx config group writable and fails without this
      # but the permission is actually not needed and the image still starts
      #- FOWNER

networkpolicy:
  enabled: true
  preset:
    namespaceIsolation: true
    egress:
      toFQDNs:
        - appslist.heimdall.site  # fetch the list of supported apps
      toNetworkLabels:
        - custom.network/heimdall-integrated

livenessProbe:
  enabled: true
  http:
    path: /
    port: 80

readinessProbe:
  enabled: true
  http:
    path: /
    port: 80
