# Source: kargo/charts/kargo/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    helm.sh/chart: kargo-1.11.4
    app.kubernetes.io/name: kargo
    app.kubernetes.io/instance: kargo
    app.kubernetes.io/version: "v1.11.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: api
  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: kargo
      app.kubernetes.io/instance: kargo
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        helm.sh/chart: kargo-1.11.4
        app.kubernetes.io/name: kargo
        app.kubernetes.io/instance: kargo
        app.kubernetes.io/version: "v1.11.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: api
      annotations:
        configmap/checksum: abe0c1e438129a883fb01f9f89ce4066c234376e4df6cedc16a4fee8befcb9aa
        secret/checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      serviceAccountName: kargo-api
      containers:
      - name: api
        image: ghcr.io/akuity/kargo:v1.11.4
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/kargo", "api"]
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: limits.cpu
        envFrom:
        - configMapRef:
            name: kargo-api
        - secretRef:
            name: kargo-api-credentials
        ports:
        - name: h2c
          containerPort: 8080
          protocol: TCP
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 30
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
        resources:
          {}