# Source: kargo/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-api-credentials
spec:
  target:
    name: kargo-api-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ADMIN_ACCOUNT_PASSWORD_HASH: |-
          {{ index . "ADMIN_ACCOUNT_PASSWORD_HASH" }}
        ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: |-
          {{ index . "ADMIN_ACCOUNT_TOKEN_SIGNING_KEY" }}
  data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb51f598-1312-49b4-828f-b4be00c969e9
        property: password_hash
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: cb51f598-1312-49b4-828f-b4be00c969e9
        property: signing_key