# Source: kargo/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-prod-kubeconfig
spec:
  target:
    name: kargo-prod-kubeconfig
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        kubeconfig.yaml: |-
          {{ index . "kubeconfig.yaml" }}
  data:
    - secretKey: kubeconfig.yaml
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: a788ae4c-9ff9-401f-86bc-b4d201142b35
        property: kubeconfig.yaml