# Source: home-assistant/charts/home-assistant/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-external-secret
spec:
  target:
    name: home-assistant-external-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_HOMEMATIC_PASSWORD: |-
          {{ index . "SECRET_HOMEMATIC_PASSWORD" }}
        SECRET_HOMEMATIC_USER: |-
          {{ index . "SECRET_HOMEMATIC_USER" }}
        SECRET_JELLYFIN_APIKEY: |-
          {{ index . "SECRET_JELLYFIN_APIKEY" }}
        SECRET_MQTT_PASSWORD: |-
          {{ index . "SECRET_MQTT_PASSWORD" }}
        SECRET_MQTT_USER: |-
          {{ index . "SECRET_MQTT_USER" }}
  data:
    - secretKey: SECRET_HOMEMATIC_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0962728-e7f8-4cfc-a983-b39e00bb1ae0
        property: homematic_password
    - secretKey: SECRET_HOMEMATIC_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0962728-e7f8-4cfc-a983-b39e00bb1ae0
        property: homematic_username
    - secretKey: SECRET_JELLYFIN_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0962728-e7f8-4cfc-a983-b39e00bb1ae0
        property: jellyfin_apikey
    - secretKey: SECRET_MQTT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0962728-e7f8-4cfc-a983-b39e00bb1ae0
        property: mqtt_password
    - secretKey: SECRET_MQTT_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c0962728-e7f8-4cfc-a983-b39e00bb1ae0
        property: mqtt_username