ingress:
  enabled: false
  host: "traefik-external.svc.elda"

traefik:
  deployment: 
    replicas: 2  # todo: remove for autoscale

  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "10.0.4.201"
