# Source: mosquitto/charts/mosquitto/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-users
spec:
  target:
    name: mosquitto-users
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        mosquitto_passwd: |-
          {{ index . "mosquitto_passwd" }}
  data:
    - secretKey: mosquitto_passwd
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 741a9f4f-684f-4cba-aef2-b3aa00b47396
        property: mosquitto_passwd