# Source: apps-generator/templates/kargo-resources.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-app-traefik-external
  annotations:
    kargo.akuity.io/keep-namespace: "true"