# Source: apps-generator/templates/kargo-resources.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-app-local-path-provisioner
  namespace: kargo-app-local-path-provisioner
spec:
  promotionPolicies:
    - stageSelector:
        name: test
      autoPromotionEnabled: false
    - stageSelector:
        name: prod
      autoPromotionEnabled: false