# Source: apps-generator/templates/kargo-resources.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-app-hello-world-simple
  namespace: kargo-app-hello-world-simple
spec:
  promotionPolicies:
    - stageSelector:
        name: test
      autoPromotionEnabled: false