# Source: apps-generator/templates/kargo-resources.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-app-n8n
  namespace: kargo-app-n8n
spec:
  promotionPolicies:
    - stageSelector:
        name: prod
      autoPromotionEnabled: true