# Source: step-ca/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-certificates-provisioner-password
spec:
  target:
    name: step-certificates-provisioner-password
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ index . "password" }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 707ff9d9-d84b-42e2-93a2-b3e000f93a12
        property: password