# Source: step-ca/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-certificates-ca-password
spec:
  target:
    name: step-certificates-ca-password
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: |-
          {{ index . "password" }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7b82f671-dbbe-4b80-9bd3-b3dd00aecf20
        property: password