# Source: step-ca/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-certificates-secrets
spec:
  target:
    name: step-certificates-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        intermediate_ca_key: |-
          {{ index . "intermediate_ca_key" }}
  data:
    - secretKey: intermediate_ca_key
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 91a2e43d-5fba-478a-b436-b3e000e9b7ed
        property: intermediate_ca_key