---
# Source: step-ca/charts/step-certificates/templates/bootstrap.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: step-certificates-config
  namespace: step-ca
  labels:
    helm.sh/chart: step-certificates-1.30.1
    app.kubernetes.io/name: step-certificates
    app.kubernetes.io/instance: step-ca
    app.kubernetes.io/version: "0.30.2"
    app.kubernetes.io/managed-by: Helm