# Source: adguard-sync/charts/adguard-sync/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-replica-credentials
spec:
  target:
    name: adguard-replica-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        REPLICA1_PASSWORD: |-
          {{ index . "REPLICA1_PASSWORD" }}
        REPLICA1_USERNAME: |-
          {{ index . "REPLICA1_USERNAME" }}
  data:
    - secretKey: REPLICA1_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 211f4a82-531f-4187-9a4c-b3920134f557
        property: password
    - secretKey: REPLICA1_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 211f4a82-531f-4187-9a4c-b3920134f557
        property: username