# Source: adguard-sync/charts/adguard-sync/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-origin-credentials
spec:
  target:
    name: adguard-origin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ORIGIN_PASSWORD: |-
          {{ index . "ORIGIN_PASSWORD" }}
        ORIGIN_USERNAME: |-
          {{ index . "ORIGIN_USERNAME" }}
  data:
    - secretKey: ORIGIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0686e3e1-8737-42ff-b267-b3b20135d9e0
        property: password
    - secretKey: ORIGIN_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0686e3e1-8737-42ff-b267-b3b20135d9e0
        property: username