apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "postgresdb.cnpg.clusterName" . }}-scheduled-backup
  labels:
    app.kubernetes.io/component: database-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  backupOwnerReference: self  # TODO: cluster or self??
  immediate: false
  cluster:
    name: {{ include "postgresdb.cnpg.clusterName" . }}

  # configure backup type - https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#performing-a-base-backup
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
