apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "postgresdb.cnpg.clusterName" . }}
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresdb
    app.kubernetes.io/instance: {{ include "postgresdb.cnpg.clusterName" . }}
    app.kubernetes.io/version: {{ .Values.clusterGeneration | quote }}
    
spec:
  # Documentation: https://cloudnative-pg.io/documentation/1.27/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
  instances: {{ .Values.postgres.instances }}
  description: "General purpose PostgreSQL cluster"
  #imageName: "ghcr.io/cloudnative-pg/postgresql:16.3-bullseye"
  primaryUpdateStrategy: unsupervised  # default, automated. opposed to 'supervised'
  enablePDB: true

  # https://cloudnative-pg.io/documentation/1.27/applications/#secrets
  # -> kubectl get secret -n cloudnative-pg postgresdb-superuser -o jsonpath='{.data.password}' | base64 --decode
  enableSuperuserAccess: true
  #superuserSecret: "xxx TODO xxx"
  
  storage:
    #storageClass: longhorn-postgres-replica-storage  # TODO: could use local-storage-provisioner?
    storageClass: local-path-auto-delete
    size: 2Gi
  walStorage:
    #storageClass: longhorn-postgres-replica-storage  # TODO: could use local-storage-provisioner?
    storageClass: local-path-auto-delete
    size: 2Gi

  # required for garage s3: https://garagehq.deuxfleurs.fr/cookbook/clients.html
  env:
    - name: AWS_S3_FORCE_PATH_STYLE
      value: "true"
    - name: AWS_DEFAULT_REGION
      value: garage

  # prometheus
  #monitoring:
  #  enablePodMonitor: true  # TODO

  # TODO: 
  # affinity:
  #   enablePodAntiAffinity: true
  # topologySpreadConstraints:

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-s3-object-store

  {{- if .Values.restore.enabled }}
  # https://cloudnative-pg.io/documentation/current/recovery/
  # https://cloudnative-pg.io/plugin-barman-cloud/docs/migration/
  bootstrap:
    recovery:
      source: {{ include "postgresdb.cnpg.previousClusterName" . }}

  externalClusters:
    - name: {{ include "postgresdb.cnpg.previousClusterName" . }}  # any name, that is references in recovery.source  
      plugin:
        name: barman-cloud.cloudnative-pg.io
        isWALArchiver: true
        parameters:
          barmanObjectName: garage-s3-object-store
          serverName: {{ include "postgresdb.cnpg.previousClusterName" . }}  # name of the postgresdb cluster to restore from
  {{- end }}
