# Source: nodered/charts/nodered/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodered-external-secret
spec:
  target:
    name: nodered-external-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MY_NODERED_ADMIN_PASSWORD: |-
          {{ index . "MY_NODERED_ADMIN_PASSWORD" }}
        MY_NODERED_ADMIN_USERNAME: |-
          {{ index . "MY_NODERED_ADMIN_USERNAME" }}
        MY_NODERED_CREDENTIAL_SECRET: |-
          {{ index . "MY_NODERED_CREDENTIAL_SECRET" }}
  data:
    - secretKey: MY_NODERED_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 230c480a-b2db-4bc4-9186-b38a009fa815
        property: password
    - secretKey: MY_NODERED_ADMIN_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 230c480a-b2db-4bc4-9186-b38a009fa815
        property: username
    - secretKey: MY_NODERED_CREDENTIAL_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 230c480a-b2db-4bc4-9186-b38a009fa815
        property: credentialSecret