apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-mediarr-smb-creds
spec:
  target:
    name: jellyfin-mediarr-smb-creds
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        domain: |-
          WORKGROUP
        password: |-
          {{ index . "password" }}
        username: |-
          {{ index . "username" }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 08fcb826-138c-4ca7-ae96-b3a9012fc292
        property: password
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 08fcb826-138c-4ca7-ae96-b3a9012fc292
        property: username