# Source: jellyfin/charts/jellyfin/charts/smbstorage/templates/pvc-static.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jellyfin-media-pvc-smb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  # empty to disable dynamic provisioning via storageclass
  volumeName: "jellyfin-media-pv-smb"
  storageClassName: ""