---
# Source: authentik/charts/authentik/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: "authentik"
  labels:
    helm.sh/chart: "authentik-2026.8.3"
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2026.8.3"
data:  
  AUTHENTIK_DISABLE_STARTUP_ANALYTICS: "dHJ1ZQ=="
  AUTHENTIK_DISABLE_UPDATE_CHECK: "ZmFsc2U="
  AUTHENTIK_EMAIL__PORT: "NTg3"
  AUTHENTIK_EMAIL__TIMEOUT: "MzA="
  AUTHENTIK_EMAIL__USE_SSL: "ZmFsc2U="
  AUTHENTIK_EMAIL__USE_TLS: "ZmFsc2U="
  AUTHENTIK_ENABLED: "dHJ1ZQ=="
  AUTHENTIK_ERROR_REPORTING__ENABLED: "ZmFsc2U="
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: "azhz"
  AUTHENTIK_ERROR_REPORTING__SEND_PII: "ZmFsc2U="
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: "L2dlb2lwL0dlb0xpdGUyLUFTTi5tbWRi"
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: "L2dlb2lwL0dlb0xpdGUyLUNpdHkubW1kYg=="
  AUTHENTIK_LOG_LEVEL: "aW5mbw=="
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: "Z2hjci5pby9nb2F1dGhlbnRpay8lKHR5cGUpczolKHZlcnNpb24pcw=="
  AUTHENTIK_POSTGRESQL__HOST: "ZmlsZTovLy9tbnQvcGdjcmVkcy9ob3N0"
  AUTHENTIK_POSTGRESQL__NAME: "ZmlsZTovLy9tbnQvcGdjcmVkcy9kYm5hbWU="
  AUTHENTIK_POSTGRESQL__PASSWORD: "ZmlsZTovLy9tbnQvcGdjcmVkcy9wYXNzd29yZA=="
  AUTHENTIK_POSTGRESQL__PORT: "NTQzMg=="
  AUTHENTIK_POSTGRESQL__USER: "ZmlsZTovLy9tbnQvcGdjcmVkcy91c2VybmFtZQ=="
  AUTHENTIK_WEB__PATH: "Lw=="