# Step-CA Certificates ConfigMap
# Fill in the certificates after running: step ca init
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
data:
  root_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIB4DCCAWWgAwIBAgIQIgUX77a8MRnxSIMtw9eG2DAKBggqhkjOPQQDAzAjMSEw
    HwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJvb3QgQ0EwHhcNMjYwMzA3MjEwNzA1
    WhcNMzYwMzA0MjEwNzA1WjAjMSEwHwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJv
    b3QgQ0EwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAASlrAvhjaBxcdnKK+U+NA99Incj
    rU4LH0d81IrhVi2noQFzjbYcDGCxu5ABKM/tyPwIOXZ7w0D2CxRj74Sv7dDmX6Gl
    PD67NvgrhbJ5i6ycBTQuMJEO32C34z5IL2CgsQajXjBcMA4GA1UdDwEB/wQEAwIB
    BjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBSgLhQbv8nqjQj0aB4KEK5y
    e+ChYDAXBgNVHR4BAf8EDTALoAkwB4IFLmVsZGEwCgYIKoZIzj0EAwMDaQAwZgIx
    ALKbBTCyT84OhXeL7EzBMzwXkIeJi8jbBj9T12lNgehruzhYWyESrCZWR63kZCo8
    wAIxANyRKmx/srCgcE9TvVpuGenztFi1exN7XxptNZMCB7ZNsBL8x9iULINbqdft
    TSfYrA==
    -----END CERTIFICATE-----
  intermediate_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIB7TCCAXSgAwIBAgIRANbsor9FpD64QFW646jyayYwCgYIKoZIzj0EAwMwIzEh
    MB8GA1UEAxMYc3RlcC1jYS5zdmMuZWxkYSBSb290IENBMB4XDTI2MDMwNzIxMDcw
    N1oXDTM2MDMwNDIxMDcwN1owRjEZMBcGA1UEChMQc3RlcC1jYS5zdmMuZWxkYTEp
    MCcGA1UEAxMgc3RlcC1jYS5zdmMuZWxkYSBJbnRlcm1lZGlhdGUgQ0EwWTATBgcq
    hkjOPQIBBggqhkjOPQMBBwNCAASdhPuHlo26kffhc8S+EGfT+qNv4ws6DRzr+Ndc
    YADlqGckLMZ2gqFgsJkHzoPshoriumeny2YpxxKXCu2WlUBSo2YwZDAOBgNVHQ8B
    Af8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUGHx6CHcgvlXV
    aPEmDjJYBM0StxIwHwYDVR0jBBgwFoAUoC4UG7/J6o0I9GgeChCucnvgoWAwCgYI
    KoZIzj0EAwMDZwAwZAIwdwgidMkQFb1YWuynbSr0p3BTIrVwer8BjC7AlgIo87VX
    K3ume8Msoy47UnBL04oIAjApTR2Xzt5uLp0np+Oag/XXm0rupAoln/10xUuTlmgH
    6CjQ+VnPLJ3YsXKMKdtWvkc=
    -----END CERTIFICATE-----
