# Step-CA Certificates ConfigMap
# Fill in the certificates after running: step ca init
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
data:
  root_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIB3zCCAWagAwIBAgIRAMpmwhmoKNieIIZ86215WlkwCgYIKoZIzj0EAwMwIzEh
    MB8GA1UEAxMYc3RlcC1jYS5zdmMuZWxkYSBSb290IENBMB4XDTI2MDMwNzIxNTEy
    MVoXDTM2MDMwNDIxNTEyMVowIzEhMB8GA1UEAxMYc3RlcC1jYS5zdmMuZWxkYSBS
    b290IENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEIEDmY6XzQpCAkxTx68hezCUv
    vWVx2Ukj2ny27Cj0n6A5yf0/rJsvoE6PAQJztlIR8WkU7+YiifjYxhIdhrTxfIGX
    kNnbJb/zMZmFoNRDb163xM/yERFph3A6R4SIyyT4o14wXDAOBgNVHQ8BAf8EBAMC
    AQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU/S+qX2Uy1rBmkRoZUs8F
    37H2SIswFwYDVR0eAQH/BA0wC6AJMAeCBS5lbGRhMAoGCCqGSM49BAMDA2cAMGQC
    MFiDh7zbCCnLuFOn80Pd2N8rnnmfyRFU/nqqRuJPYi7m+cEGuWF177zsnp4vYOCl
    6AIwUn6v96Ncnuy9Mtx7GHa4XhPZZzstTnZlsQXEPeFlkMoeJCtV8Ld5q2xNDMp1
    UBSh
    -----END CERTIFICATE-----
  intermediate_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIB7DCCAXOgAwIBAgIQBJLx/aO+0fpr+N5LkOa6YzAKBggqhkjOPQQDAzAjMSEw
    HwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJvb3QgQ0EwHhcNMjYwMzA3MjE1MTIz
    WhcNMzYwMzA0MjE1MTIzWjBGMRkwFwYDVQQKExBzdGVwLWNhLnN2Yy5lbGRhMSkw
    JwYDVQQDEyBzdGVwLWNhLnN2Yy5lbGRhIEludGVybWVkaWF0ZSBDQTBZMBMGByqG
    SM49AgEGCCqGSM49AwEHA0IABNYWfZatRQjX6/NEVo+kjelVBI0SDl78e6XHSur2
    oiOxusMxOreenpX+YS5wSYwaEA3oU1FApVA1L2+GI4LSK9mjZjBkMA4GA1UdDwEB
    /wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSC52SgVpHcgJMo
    t4rKWpmNgX8baDAfBgNVHSMEGDAWgBT9L6pfZTLWsGaRGhlSzwXfsfZIizAKBggq
    hkjOPQQDAwNnADBkAjBwl3SF+R+jzdgEB4fO4OEHIYQd4tAgFAra8zpSEoAmOZTY
    GSUBrC+SU8gtEdqT/4sCMF2dUQT/f7ig0hXOtz/eH90JLb65Q/nUEn/ZW/n954RM
    fPtjyRRipvXhQVplD6yF+Q==
    -----END CERTIFICATE-----
