# Step-CA Certificates ConfigMap
# Fill in the certificates after running: step ca init
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
data:
  root_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIB6DCCAW+gAwIBAgIQc6ZT98ZRMuEIVM6g2Qs67zAKBggqhkjOPQQDAzAjMSEw
    HwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJvb3QgQ0EwHhcNMjYwMzA4MTEwODQ5
    WhcNMzYwMzA1MTEwODQ5WjAjMSEwHwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJv
    b3QgQ0EwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQMouekWag2QNfYxXfeRdb8BTJD
    hTEERHk7BsU2lJhR8abRmav/PTv1oz8I6bHSnA8STN0uFNt6vL1FkG5z5eQ8xv5I
    036fGbgRGJRgTtjvvADnLp7nV4lyKkH/lwHb50ijaDBmMA4GA1UdDwEB/wQEAwIB
    BjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTiAmoArDS8KLEbUr28IGMV
    JfvpATAhBgNVHR4BAf8EFzAVoBMwB4IFLmVsZGEwCIIGLmxvY2FsMAoGCCqGSM49
    BAMDA2cAMGQCMAJU0zXPQmuvocGwMs3IIRt8lB0ZFf+pULnfJh87girXK0KDCsU8
    7uvKM7xVu1KDvgIwL1JNPTkzX6OB8gbyaKUwT6rOZI+MAG1wCxZkLpclwqTLVRMD
    fzVNRiG2HnGJKcE1
    -----END CERTIFICATE-----
  intermediate_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICFDCCAZqgAwIBAgIQEKqyXhcTSMfrlTREs2MaxDAKBggqhkjOPQQDAzAjMSEw
    HwYDVQQDExhzdGVwLWNhLnN2Yy5lbGRhIFJvb3QgQ0EwHhcNMjYwMzA4MTEwODUx
    WhcNMzEwMzA3MTEwODUxWjArMSkwJwYDVQQDEyBzdGVwLWNhLnN2Yy5lbGRhIElu
    dGVybWVkaWF0ZSBDQTB2MBAGByqGSM49AgEGBSuBBAAiA2IABOeq8v2zDg/1650v
    Iditpjl7LR0yV50tWm0tdgfTRKHmCaVNkhSssYhhKJPk8bgX7svkkrqDEeHvfYo3
    aKqwQrRM9QgTJJwBoE8AUckyRTuX0y48cX2SSHiKh/Dw+5V2rqOBijCBhzAOBgNV
    HQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUkBGjurUO
    DyuEXznObjrsRVgtwCwwHwYDVR0jBBgwFoAU4gJqAKw0vCixG1K9vCBjFSX76QEw
    IQYDVR0eAQH/BBcwFaATMAeCBS5lbGRhMAiCBi5sb2NhbDAKBggqhkjOPQQDAwNo
    ADBlAjBKSlnnUY9dzN9vIcKkkKGXxC3EB0xtofOyRCu+5CpTP89f3bKLR6UuVuWo
    w9VOLSECMQDtwpB+7pNV7G/iZbgF95qW/KR7DZWDOnR4fHGiI/xUER9r2s/kOtJR
    5+Y6zQY+ZhI=
    -----END CERTIFICATE-----
