# Step-CA Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-config
data:
  # TODO: could set durations for acme provisioner:
  #  "claims": {
  #    "minTLSCertDuration": "24h",
  #    "maxTLSCertDuration": "8760h",  // 1 year
  #    "defaultTLSCertDuration": "2160h"  // 90 days (Let's Encrypt default)
  #  }
  # TODO: requireEAB *could* be enabled for better security, but it would require manual steps to create the EAB credentials for each ACME account
  ca.json: |-
    {
      "root": "/home/step/certs/root_ca.crt",
      "federatedRoots": [],
      "crt": "/home/step/certs/intermediate_ca.crt",
      "key": "/home/step/secrets/intermediate_ca_key",
      "address": ":9000",
      "insecureAddress": "",
      "dnsNames": [
        "step-ca.svc.elda",
        "ca.svc.elda",
        "step-certificates.step-ca.svc.cluster.local"
      ],
      "logger": {
        "format": "json"
      },
      "db": {
        "type": "badgerv2",
        "dataSource": "/home/step/db"
      },
      "authority": {
        "enableAdmin": false,
        "provisioners": [
          {
            "type": "JWK",
            "name": "ju@step-ca.svc.elda",
            "key": {
              "use": "sig",
              "kty": "EC",
              "kid": "-y-J6y25GjFHs2trO3P-WkhFVspDeBu1e6JW5JYNuB4",
              "crv": "P-256",
              "alg": "ES256",
              "x": "FCYCIFmvxYXD9sqH1XX9Suth7CiTdNNnupl4OAPxR4o",
              "y": "UAo1k0ognsVUJ8J8hTRAfTp8Bv3D9IckKhvcLKiF_OU"
            },
            "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoicmR1bEwwN3B3YWtFS0s1dVhTenJaZyJ9.ocOzzsG-RVc4rl7B7PUdnFEq40W5hiFTxvDA5rxPO3QcNMdjpV1QSw.75ubejbRfBnNpl_U.vGemv66BkKr-dd6E7Q55ofxPPbqYJ5fHNpRvOuEvDSb9HVIJu1LRz-j5INTRd9PWyIUGD5UI6x6NUKyu41vRCDQI6iTRESxg29PdgJGVoxR4Lbv7r_VevNma9uzS5CdlhC-RBnEKPVnXfFjBIhbvFz6c4tLISO_tbIRa3PQMuQsUYH3t7eeH4DxMg_Wivc81KP9Upew-qWrUq5vtqVglF5Rg4_IeMmwdOghXty0ZUpbC4HZJUodYnCYAmqGkLZgeKn2BvDwM9ajy8qkpcFudunUdOaiUltYmLprV2K8_5Q5-WtuMhUt46IoWiCl9IvKwI_gwxAVTMWFFH8vtojw.rXEi5HQhtopQp60diWFi1Q"
          },
          {
            "type": "ACME",
            "name": "elda",
            "forceCN": false,
            "requireEAB": false,
            "challenges": [
              "http-01"
            ]
          }
        ],
        "policy": {
          "x509": {
            "allow": {
              "dns": [
                "*.elda",
                "*.svc.elda",
                "*.test.svc.elda"
              ]
            },
            "allowWildcardNames": false
          }
        }
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      }
    }
  defaults.json: |-
    {
      "ca-url": "https://step-ca.svc.elda",
      "ca-config": "/home/step/config/ca.json",
      "fingerprint": "f1d3842e3bf037d75383495e22ff82dd15e76508cbc7b2a0fc0386048462e733",
      "root": "/home/step/certs/root_ca.crt"
    }
