# Step-CA Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-config
data:
  # TODO: could set durations for acme provisioner:
  #  "claims": {
  #    "minTLSCertDuration": "24h",
  #    "maxTLSCertDuration": "8760h",  // 1 year
  #    "defaultTLSCertDuration": "2160h"  // 90 days (Let's Encrypt default)
  #  }
  # TODO: requireEAB *could* be enabled for better security, but it would require manual steps to create the EAB credentials for each ACME account
  ca.json: |-
    {
      "root": "/home/step/certs/root_ca.crt",
      "federatedRoots": [],
      "crt": "/home/step/certs/intermediate_ca.crt",
      "key": "/home/step/secrets/intermediate_ca_key",
      "address": ":9000",
      "insecureAddress": "",
      "dnsNames": [
        "step-ca.svc.elda",
        "ca.svc.elda",
        "step-certificates.step-ca.svc.cluster.local"
      ],
      "logger": {
        "format": "json"
      },
      "db": {
        "type": "badgerv2",
        "dataSource": "/home/step/db"
      },
      "authority": {
        "enableAdmin": false,
        "provisioners": [
          {
            "type": "JWK",
            "name": "ju@step-ca.svc.elda",
            "key": {
              "use": "sig",
              "kty": "EC",
              "kid": "RT23HqjnaZjGEmCOsehPTzDhAIxPSH-Ov4NaiU2AsR8",
              "crv": "P-256",
              "alg": "ES256",
              "x": "HHr7dLu9HWTiXMel-wt1EbbiJieKlJrSWDC44QtFzso",
              "y": "HbimK6g41bmKgKGuUz5xLvOgOX8X6x9EHyGnCEgUAYc"
            },
            "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiTGVJS25BVUFzVENLb2xfaXJ1eFJWZyJ9.eD8EzVOl5c28RQLTjMhVYx4mATO2_95QhMr8yIR6bsQyA3C5F2YEzQ.YI2tMRm-f1U986Qh.cKXePShLAVZwAfOTdzMFo2WYd8TtferI3FLTgTGXekgw24Bgks66xNGLrTWGEY7mOGBdKoWaFb_N0t5lvM2nG_UACuqdnH2B9rFZeaQHx-D5-u9G_hm_uZFWEFeGnIpAgzu0_V_GtRWk0Ur49LozTbs8TkSiFuDD1UGTq-BgOvtNYn_YJpL3umX-eW1N84Xifizeg3HUS7OyPwNagr8UGsNFXw1VyWrtSKFzeMwwkxfr1MOSnzK5-0P3XdhMLBfoxLry6XM6Af_qlV1-1_SZA1yy35avLyGXgkCHc9T2ZCnx-9iSQ6xLGY__MJGEfrdhMiC_IwgVbmMY0GOr86k.VFQG7X8HZrUKK1JRYWPIwQ"
          },
          {
            "type": "ACME",
            "name": "elda",
            "forceCN": false,
            "requireEAB": false,
            "challenges": [
              "http-01"
            ]
          }
        ],
        "policy": {
          "x509": {
            "allow": {
              "dns": [
                "*.elda",
                "*.svc.elda",
                "*.test.svc.elda"
              ]
            },
            "allowWildcardNames": false
          }
        }
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      }
    }
  defaults.json: |-
    {
      "ca-url": "https://step-ca.svc.elda",
      "ca-config": "/home/step/config/ca.json",
      "fingerprint": "4418168f9e790a07e2c121b2cdcceca56cff3e4434de80ff797684da009aa273",
      "root": "/home/step/certs/root_ca.crt"
    }
