apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-internal
spec:
  acme:
    server: https://step-certificates.step-ca.svc.cluster.local/acme/elda/directory
    # base64-encoded root CA PEM from certs-configmap.yaml root_ca.crt
    # generate with: 
    #   - kubectl get cm step-certificates-certs -n step-ca -o jsonpath='{.data.root_ca\.crt}' | base64 -w0
    #  or
    #   -  yq '.data."root_ca.crt"' resources/certs-configmap.yaml | base64 -w0
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0RENDQVdXZ0F3SUJBZ0lRSWdVWDc3YThNUm54U0lNdHc5ZUcyREFLQmdncWhrak9QUVFEQXpBak1TRXcKSHdZRFZRUURFeGh6ZEdWd0xXTmhMbk4yWXk1bGJHUmhJRkp2YjNRZ1EwRXdIaGNOTWpZd016QTNNakV3TnpBMQpXaGNOTXpZd016QTBNakV3TnpBMVdqQWpNU0V3SHdZRFZRUURFeGh6ZEdWd0xXTmhMbk4yWXk1bGJHUmhJRkp2CmIzUWdRMEV3ZGpBUUJnY3Foa2pPUFFJQkJnVXJnUVFBSWdOaUFBU2xyQXZoamFCeGNkbktLK1UrTkE5OUluY2oKclU0TEgwZDgxSXJoVmkybm9RRnpqYlljREdDeHU1QUJLTS90eVB3SU9YWjd3MEQyQ3hSajc0U3Y3ZERtWDZHbApQRDY3TnZncmhiSjVpNnljQlRRdU1KRU8zMkMzNHo1SUwyQ2dzUWFqWGpCY01BNEdBMVVkRHdFQi93UUVBd0lCCkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUJNQjBHQTFVZERnUVdCQlNnTGhRYnY4bnFqUWowYUI0S0VLNXkKZStDaFlEQVhCZ05WSFI0QkFmOEVEVEFMb0Frd0I0SUZMbVZzWkdFd0NnWUlLb1pJemowRUF3TURhUUF3WmdJeApBTEtiQlRDeVQ4NE9oWGVMN0V6Qk16d1hrSWVKaThqYkJqOVQxMmxOZ2VocnV6aFlXeUVTckNaV1I2M2taQ284CndBSXhBTnlSS214L3NyQ2djRTlUdlZwdUdlbnp0RmkxZXhON1h4cHROWk1DQjdaTnNCTDh4OWlVTElOYnFkZnQKVFNmWXJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    privateKeySecretRef:
      name: step-ca-acme-account-key
    solvers:
      - http01: # https://cert-manager.io/docs/configuration/acme/http01/
          ingress:
            ingressClassName: traefik
            ingressTemplate:
              metadata:
                annotations:
                  traefik.ingress.kubernetes.io/router.middlewares: "traefik-common-internal-access-allowlist@kubernetescrd"
