apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-internal
spec:
  acme:
    server: https://step-certificates.step-ca.svc.cluster.local/acme/elda/directory
    # base64-encoded root CA PEM from certs-configmap.yaml root_ca.crt
    # generate with: 
    #   - kubectl get cm step-certificates-certs -n step-ca -o jsonpath='{.data.root_ca\.crt}' | base64 -w0
    #  or
    #   -  yq '.data."root_ca.crt"' resources/certs-configmap.yaml | base64 -w0
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI2ekNDQVhDZ0F3SUJBZ0lSQU9EVnJ6emthRDZ3ZlQ0OFVwKzk2bXd3Q2dZSUtvWkl6ajBFQXdNd0l6RWgKTUI4R0ExVUVBeE1ZYzNSbGNDMWpZUzV6ZG1NdVpXeGtZU0JTYjI5MElFTkJNQjRYRFRJMk1ETXdOekl4TlRndwpORm9YRFRNMk1ETXdOREl4TlRnd05Gb3dJekVoTUI4R0ExVUVBeE1ZYzNSbGNDMWpZUzV6ZG1NdVpXeGtZU0JTCmIyOTBJRU5CTUhZd0VBWUhLb1pJemowQ0FRWUZLNEVFQUNJRFlnQUVnUC9lMnM0bS9rV04xcFJkQktCV2xCRGMKRG5odXhNT1NkSVc4RFBhL2VXczZCMHhwb05xbEJUWklkK3FpRTB4dHBtclI5bkNjTDF6NFBCWUZ2ZDN2ZUlvbQpDMnBKS2Z0VFNTZURIenpnNkt2SlQ2clB5Ync1azBrU09JUGRJdld4bzJnd1pqQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEFkQmdOVkhRNEVGZ1FVUm1sRjJVaUNGNnBFSDg5ck1Sa3oKYUFzUzhqd3dJUVlEVlIwZUFRSC9CQmN3RmFBVE1BZUNCUzVsYkdSaE1BaUNCaTVzYjJOaGJEQUtCZ2dxaGtqTwpQUVFEQXdOcEFEQm1BakVBMTVacUtJeUhBR0k5QXNydmJGSFZnMkp3YmxUbSswVDA1Rk5wdFJqSFV5NXQ4LzhqCkhXQ2JPUDUxUTBHOXVSOWhBakVBcm9Mc0JxQ0FrcUFnZWxsSUdFWTEvaEZuYlhBanJQQ293c3Q0Rk1xeUp3cDQKUlhtOVMwYzdRSlA1UFVQemNwUVoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    privateKeySecretRef:
      name: step-ca-acme-account-key
    solvers:
      - http01: # https://cert-manager.io/docs/configuration/acme/http01/
          ingress:
            ingressClassName: traefik
            #ingressTemplate:
            #  metadata:
            #    annotations:
            #      # TODO: does not allow access from within the cluster...
            #      traefik.ingress.kubernetes.io/router.middlewares: "traefik-common-internal-access-allowlist@kubernetescrd"
