apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: Argocd Project
  sourceRepos:
    - {{ .Values.repoUrl }}
  destinations:
    - namespace: {{ .Values.namespace }}
      server: {{ .Values.server }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
