apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.server }}
  project: cilium
  sources:
    - helm:
        version: v3
        valueFiles:
          - values.yaml
      path: 02_bootstrap/00_cilium
      repoURL: {{ .Values.repoUrl }}
      targetRevision: {{ .Values.targetRevision }}
    - path: 02_bootstrap/00_cilium/addon
      repoURL: {{ .Values.repoUrl }}
      targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: false

