apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  description: Infrastructure Component Deployments
  sourceRepos:
    - {{ .Values.repoUrl }}
    # Warning: Use the variant below (without oci://), as helm does not handle this properly. Requires a repository with enableOCI to be configured.
    #- oci://registry-1.docker.io/bitnamicharts
    - registry-1.docker.io/bitnamicharts
    # traefik
    - https://traefik.github.io/charts
    # smb-driver
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    # local-path-provisioner
    - https://github.com/rancher/local-path-provisioner
    # longhorn
    - https://charts.longhorn.io
    # bitwarden / external-secrests
    - https://charts.external-secrets.io
    # cloudnative-pg
    - https://cloudnative-pg.github.io/charts
    # minio
    - https://charts.min.io/
    # velero
    - https://vmware-tanzu.github.io/helm-charts
  destinations:
    - namespace: 'infra-*'
      server: {{ .Values.server }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
