apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.server }}
  project: argocd-project
  source:
    path: {{ .Values.baseDir}}
    repoURL: {{ .Values.mainRepo }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      version: v3
      valueFiles:
        - values.yaml
        {{- if include "apps-wrapper.targetValuesFile" $ }}
        - {{ include "apps-wrapper.targetValuesFile" $ }}
        {{- end }}
        {{- if .Values.environment }}
        - values-{{ .Values.environment }}-apps.yaml
        {{- end }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
