apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.server }}
  project: cilium-project
  sources:
    - helm:
        version: v3
        valueFiles:
          - values.yaml
          {{- if include "apps-wrapper.targetValuesFile" $ }}
          - {{ include "apps-wrapper.targetValuesFile" $ }}
          {{- end }}
      path: 02_bootstrap/00_cilium
      repoURL: {{ .Values.mainRepo }}
      targetRevision: {{ .Values.targetRevision }}
    - path: 02_bootstrap/00_cilium/resources
      repoURL: {{ .Values.mainRepo }}
      targetRevision: {{ .Values.targetRevision }}
    {{- if include "apps-wrapper.targetResourcesDir" $ }}
    - path: 02_bootstrap/00_cilium/{{ include "apps-wrapper.targetResourcesDir" $ }}
      repoURL: {{ .Values.mainRepo }}
      targetRevision: {{ .Values.targetRevision }}
    {{- end }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: false

