---
# Source: bitwarden/charts/external-secrets/templates/cert-controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-cert-controller
  namespace: bitwarden
  labels:
    
    helm.sh/chart: external-secrets-2.8.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/version: "v2.8.0"
    app.kubernetes.io/managed-by: Helm