# Source: bitwarden/charts/external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: bitwarden
  labels:
    helm.sh/chart: external-secrets-2.8.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: bitwarden
    app.kubernetes.io/version: "v2.8.0"
    app.kubernetes.io/managed-by: Helm