# Source: n8n/charts/n8n/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-key
spec:
  target:
    name: n8n-encryption-key
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        N8N_ENCRYPTION_KEY: |-
          {{ index . "N8N_ENCRYPTION_KEY" }}
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8b00da18-11ad-445f-afd7-b3940135bbf5
        property: password