---
# Source: n8n/charts/n8n/charts/longhornstorage/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  volumeName: "pvc-9bfbdd5b-a12f-41aa-ada3-84dcfd1ae2e4"
  resources:
    requests:
      storage: 200Mi