# Source: cloudnative-pg-operator/charts/cloudnative-pg/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudnative-pg-operator
  labels:
    helm.sh/chart: cloudnative-pg-0.29.0
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cloudnative-pg-operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg-operator
subjects:
- kind: ServiceAccount
  name: cloudnative-pg-operator
  namespace: cloudnative-pg