---
# Source: cloudnative-pg-operator/charts/cloudnative-pg/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudnative-pg-operator
  namespace: cloudnative-pg
  labels:
    helm.sh/chart: cloudnative-pg-0.29.0
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: cloudnative-pg-operator
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm