---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-plugin-barman-cloud
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - backups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters/finalizers
    verbs:
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-plugin-barman-cloud-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnpg-plugin-barman-cloud
subjects:
  - kind: ServiceAccount
    name: cnpg-plugin-barman-cloud
    namespace: cloudnative-pg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg-plugin-barman-cloud-crds
rules:
  - apiGroups:
      - barmancloud.cnpg.io
    resources:
      - objectstores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - barmancloud.cnpg.io
    resources:
      - objectstores/finalizers
    verbs:
      - update
  - apiGroups:
      - barmancloud.cnpg.io
    resources:
      - objectstores/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-plugin-barman-cloud-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnpg-plugin-barman-cloud-crds
subjects:
  - kind: ServiceAccount
    name: cnpg-plugin-barman-cloud
    namespace: cloudnative-pg
