# https://github.com/kubernetes-csi/csi-driver-smb/tree/master/charts
helm:
  chart: csi-driver-smb
  version: v1.18.0
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
