# Reference: https://github.com/zebpalmer/kubernetes-transmission-openvpn
ingress:
  host: transmission.srv.elda
  accessControl:
    externalAccessAllowed: false

image:
  name: haugene/transmission-openvpn
  tag: 5.3.0

service:
  targetPort: 9091

livenessProbe:
  enabled: true
  override:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 2
    successThreshold: 1
    tcpSocket:
      port: 9091
    timeoutSeconds: 2

readinessProbe:
  enabled: true
  override:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 2
    successThreshold: 2
    tcpSocket:
      port: 9091
    timeoutSeconds: 2

resources:
  limits:
    memory: 1000Mi

smbstorage:
  enabled: true
  externalsecrets:
    enabled: true
    commonRemoteKey: "f460fcfc-357e-4d1b-8f5e-b32500e5c6fc"
  smb:
    host: "erolas.elda"
    share: "test"
    capacity: "1000Gi"
  mount:
    dir_mode: "0770"
    file_mode: "0660"
    uid: 1333
    gid: 1333
    capacity: "1000Gi"
    path: /data
    subPath: transmission-test


# TODO: should I add this as a volume??
#volumes:
#  - /services/transmission/settings:/settings

podSecurityContext:
  fsGroup: 1333

containerSecurityContext:
  allowPrivilegeEscalation: true  # needs to be true for privileged mode
  privileged: true  # required for TUN/TAP device access
  capabilities:
    add: ["NET_ADMIN"]

externalsecrets:
  enabled: true
  name: vpn-credentials
  commonRemoteKey: "9c1b1535-b2c4-411e-a60a-b32500e60cda"
  fields:
    OPENVPN_PROVIDER: PIA
    OPENVPN_USERNAME:
      storeRefName: bitwarden-login
      remoteProperty: username
    OPENVPN_PASSWORD:
      storeRefName: bitwarden-login
      remoteProperty: password
    TRANSMISSION_RPC_USERNAME:
      enabled: false
      storeRefName: bitwarden-login
      remoteProperty: TRANSMISSION_RPC_USERNAME
    TRANSMISSION_RPC_PASSWORD:
      enabled: false
      storeRefName: bitwarden-login
      remoteProperty: TRANSMISSION_RPC_PASSWORD
  mount:
    env: true


env: # TODO: as object
  PUID: "1333"
  PGID: "1333"
  TRANSMISSION_UMASK: "007"
  TRANSMISSION_HOME: /settings
  TRANSMISSION_DOWNLOAD_DIR: /data
  TRANSMISSION_IMCOMPLETE_DIR: /data/.incomplete
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
  TRANSMISSION_WATCH_DIR: /data/.watch
  TRANSMISSION_WATCH_DIR_ENABLED: "true"
  #TRANSMISSION_WEB_UI: combustion
  OPENVPN_CONFIG: ""
  LOCAL_NETWORK: 10.0.0.0/8  # TODO: should cover the whole cluster? 10.0.0.0/22 is the actual home subnet
  # mssfix: https://github.com/haugene/docker-transmission-openvpn/issues/257
  OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings"
  TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED: "false"
  CREATE_TUN_DEVICE: "false"
  TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "false"  # TODO: disabled for now

  # from https://github.com/zebpalmer/kubernetes-transmission-openvpn/blob/master/examples/transmission-config.yaml
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "4"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "1000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  WEBPROXY_ENABLED: "false"


extraConfig:
  volumeMounts:
    - hostPath:
        path: /dev/net/tun
        type: ""
      name: tunnel
      mountPath: /dev/net/tun


networkpolicy:
  preset:
    namespaceIsolation: true
    egress:
      toWorld: true  # TODO: could be limited to VPN provider?
