# Source: smb-driver/charts/csi-driver-smb/templates/rbac-csi-smb.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-smb-node-secret-binding
  labels:
    app.kubernetes.io/instance: "smb-driver"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "csi-driver-smb"
    app.kubernetes.io/version: "1.20.3"
    helm.sh/chart: "csi-driver-smb-1.20.3"
subjects:
  - kind: ServiceAccount
    name: csi-smb-node-sa
    namespace: smb-driver
roleRef:
  kind: ClusterRole
  name: csi-smb-node-secret-role
  apiGroup: rbac.authorization.k8s.io