---
# Source: smb-driver/charts/csi-driver-smb/templates/rbac-csi-smb.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-smb-controller-sa
  namespace: smb-driver
  labels:
    app.kubernetes.io/instance: "smb-driver"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "csi-driver-smb"
    app.kubernetes.io/version: "1.20.3"
    helm.sh/chart: "csi-driver-smb-1.20.3"