# Source: longhorn/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cifs-secret
spec:
  target:
    name: cifs-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CIFS_PASSWORD: |-
          {{ index . "CIFS_PASSWORD" }}
        CIFS_USERNAME: |-
          {{ index . "CIFS_USERNAME" }}
  data:
    - secretKey: CIFS_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b8bd47cf-bbe8-4279-8972-b35e01538c15
        property: password
    - secretKey: CIFS_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b8bd47cf-bbe8-4279-8972-b35e01538c15
        property: username