# Source: longhorn/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-crypto
spec:
  target:
    name: longhorn-crypto
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CRYPTO_KEY_CIPHER: |-
          aes-xts-plain64
        CRYPTO_KEY_HASH: |-
          sha256
        CRYPTO_KEY_PROVIDER: |-
          secret
        CRYPTO_KEY_SIZE: |-
          256
        CRYPTO_KEY_VALUE: |-
          {{ index . "CRYPTO_KEY_VALUE" }}
        CRYPTO_PBKDF: |-
          argon2i
  data:
    - secretKey: CRYPTO_KEY_VALUE
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: bb2559e5-b617-4206-adff-b33b00dc2814
        property: password