apiVersion: v2
name: cloudnative-pg-operator
description: The CloudNativePG operator, scoped to its own namespace
type: application
version: 0.1.0

dependencies:
  - name: cloudnative-pg
    version: 0.29.0
    repository: https://cloudnative-pg.github.io/charts

  - name: networkpolicy
    version: 5.1.0
    repository: oci://ghcr.io/lunarys/charts
