# Source: pgadmin/charts/pgadmin/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
spec:
  target:
    name: pgadmin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PGADMIN_DEFAULT_EMAIL: |-
          {{ index . "PGADMIN_DEFAULT_EMAIL" }}
        PGADMIN_DEFAULT_PASSWORD: |-
          {{ index . "PGADMIN_DEFAULT_PASSWORD" }}
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 67d4f7fc-5790-4f9b-82bf-b3a50112d257
        property: username
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 67d4f7fc-5790-4f9b-82bf-b3a50112d257
        property: password