# Source: postgresdb-user-operator/charts/postgresdb-user-operator/templates/metrics-reader-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresdb-user-operator-metrics-reader
  labels:
    helm.sh/chart: postgresdb-user-operator-0.3.7
    app.kubernetes.io/name: postgresdb-user-operator
    app.kubernetes.io/instance: postgresdb-user-operator
    app.kubernetes.io/version: "0.3.7"
    app.kubernetes.io/managed-by: Helm
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get