---
# Source: postgresdb-user-operator/charts/postgresdb-user-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresdb-user-operator
  labels:
    helm.sh/chart: postgresdb-user-operator-0.3.7
    app.kubernetes.io/name: postgresdb-user-operator
    app.kubernetes.io/instance: postgresdb-user-operator
    app.kubernetes.io/version: "0.3.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}