---
# Source: hello-world-simple/charts/hello-world/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-simple
  labels:
    helm.sh/chart: hello-world-0.1.0
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: hello-world-simple
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm