# Source: crowdsec/charts/externalsecrets/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
spec:
  target:
    name: crowdsec-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        bouncer_api_key: |-
          {{ index . "bouncer_api_key" }}
        cs_lapi_secret: |-
          {{ index . "cs_lapi_secret" }}
        enroll_instance_name: |-
          k8s-prod-cluster
        enroll_key: |-
          {{ index . "enroll_key" }}
        enroll_tags: |-
          k8s prod
        registration_token: |-
          {{ index . "registration_token" }}
        web_ui_password: |-
          {{ index . "web_ui_password" }}
        web_ui_user: |-
          {{ index . "web_ui_user" }}
  data:
    - secretKey: bouncer_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: bouncer_key
    - secretKey: cs_lapi_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: cs_lapi_secret
    - secretKey: enroll_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: enroll_key
    - secretKey: registration_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: registration_key
    - secretKey: web_ui_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: password
    - secretKey: web_ui_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d3abfa5f-76c9-4a8b-9cac-b42500f345a6
        property: username