apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: crowdsec
  name: crowdsec-configmap-updater-sa
  labels:
    k8s-app: crowdsec
    type: capi-register-job
    version: v1
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"